// APPLEMDT Tracker — Firebase config + shared data helpers
// Loaded as an ES module by both index.html (edit view) and display.html (TV view)

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {
  getFirestore,
  collection,
  doc,
  addDoc,
  updateDoc,
  onSnapshot,
  query,
  orderBy,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import {
  getAuth,
  signInWithEmailAndPassword,
  onAuthStateChanged,
  signOut
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";

const firebaseConfig = {
  apiKey: "AIzaSyAp-OSq87o6e4XBsSryh5ozwzw5543oKQE",
  authDomain: "pi-base-a3a09.firebaseapp.com",
  projectId: "pi-base-a3a09",
  storageBucket: "pi-base-a3a09.firebasestorage.app",
  messagingSenderId: "693559040921",
  appId: "1:693559040921:web:52651b1709f3610dd01108"
};

// The kiosk consumes a same-origin calendar file generated by GitHub Actions.
// This avoids browser CORS restrictions from the published iCloud endpoint.
const PIBASE_CALENDAR_FEED = './calendar.ics';
try {
  localStorage.setItem('pibase.calendarFeedUrl', PIBASE_CALENDAR_FEED);
} catch (error) {
  console.warn('Unable to seed PIBASE calendar feed.', error);
}

export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const auth = getAuth(app);

export {
  collection, doc, addDoc, updateDoc, onSnapshot, query, orderBy, serverTimestamp,
  signInWithEmailAndPassword, onAuthStateChanged, signOut
};

// ---- Shared constants ----
export const STAGES = [
  "Initial Appointment",
  "Packet Prep",
  "Processing Authorized",
  "Processing Scheduled",
  "Waiver",
  "Q&E",
  "Enlisted"
];

export const STAGE_SHORT = {
  "Initial Appointment": "INITIAL",
  "Packet Prep": "PACKET",
  "Processing Authorized": "AUTH'D",
  "Processing Scheduled": "SCHED",
  "Waiver": "WAIVER",
  "Q&E": "Q&E",
  "DEP": "Q&E",
  "Enlisted": "ENLISTED"
};

export function needsReview(applicant) {
  return Boolean(
    (applicant.physicalHealth && applicant.physicalHealth.trim()) ||
    (applicant.legalIssues && applicant.legalIssues.trim())
  );
}

// Match the Applicant Board's viewport-measurement behavior on the Today screen.
// Rows are measured after rendering and only the number that fits the kiosk
// viewport remains visible. This prevents Today from growing off-screen.
function fitTodayRows() {
  const todayScreen = document.getElementById('todayScreen');
  if (!todayScreen || !todayScreen.classList.contains('active')) return;

  const hint = todayScreen.querySelector('.kiosk-hint');
  const hintHeight = hint ? hint.getBoundingClientRect().height + 12 : 30;

  const fitList = (listId, reserveElement) => {
    const list = document.getElementById(listId);
    if (!list || !list.children.length) return;

    const children = Array.from(list.children);
    children.forEach(child => { child.hidden = false; });

    const listRect = list.getBoundingClientRect();
    const firstRect = children[0].getBoundingClientRect();
    if (!firstRect.height) return;

    const reserveHeight = reserveElement
      ? reserveElement.getBoundingClientRect().height + 22
      : 18;
    const availableHeight = Math.max(
      firstRect.height,
      window.innerHeight - listRect.top - hintHeight - reserveHeight
    );
    const rows = Math.max(1, Math.floor(availableHeight / firstRect.height));

    children.forEach((child, index) => {
      child.hidden = index >= rows;
    });
  };

  fitList('agendaList', null);
  fitList('actionList', todayScreen.querySelector('.metric-strip'));
}

if (typeof window !== 'undefined' && typeof document !== 'undefined') {
  const scheduleFit = () => window.requestAnimationFrame(() => fitTodayRows());
  window.addEventListener('resize', scheduleFit);

  const observer = new MutationObserver(scheduleFit);
  const startObserver = () => {
    const agenda = document.getElementById('agendaList');
    const actions = document.getElementById('actionList');
    if (agenda) observer.observe(agenda, { childList: true });
    if (actions) observer.observe(actions, { childList: true });
    scheduleFit();
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', startObserver, { once: true });
  } else {
    startObserver();
  }
}
